### ISSUE TITLE
Modified time on relation

### ISSUE THREAD

**Issue by Nropb** [berrybeat/Neo4j.Berries.OGM#48]
**Is your feature request related to a problem? Please describe.**
Currently when creating a relation between two nodes that have been connected previously, a new relationship won't be created and/or the previous relation won't be updated.

**Describe the solution you'd like**
A way to solve this would be to set a property "modifiedOn" o.s. and update existing relationships on a MERGE.

**Comment by farhadnowzari** [comment]
The feature will be as the following.

On configuring the api for a service, the developer will be able to:

* Turn on the feature to add Created or Modified dates to the nodes
* Turn on the feature to add Created or Modified dates to the relations
* Set the key in which they want to have for modified or created dates e.g. modifiedOn, createdOn,....

Then on each merge, if the feature is on and the merge is performing `create`, it will set a `create` date and if it is updating it will set a `modified` date.
